<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="traceability" nsURI="http://blackbelt.hu/judo/meta/psm/ui/traceability"
    nsPrefix="traceability">
  <eClassifiers xsi:type="ecore:EClass" name="PSMToUI">
    <eStructuralFeatures xsi:type="ecore:EReference" name="traces" upperBound="-1"
        eType="#//PSMToUITrace" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jModel" eType="ecore:EClass ../../psm_meta/src/model/psm.ecore#//JModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uiBase" eType="ecore:EClass ../../ui_meta/src/model/ui.ecore#//UIBase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PSMToUITrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="uiElements" upperBound="-1"
        eType="ecore:EClass ../../ui_meta/src/model/ui.ecore#//Identifiable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="psmElements" upperBound="-1"
        eType="ecore:EClass ../../psm_meta/src/model/psm.ecore#//JElement"/>
  </eClassifiers>
</ecore:EPackage>
